"""empty message

Revision ID: 8d2a9f910f8e
Revises: 
Create Date: 2023-10-12 23:33:24.797391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2a9f910f8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reptiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('native_habitat', sa.String(length=255), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('conservation_status', sa.Enum('extinct', 'endagered', 'threatened', 'near_treatened', 'observed', 'accepted', name='conservationstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reptiles')
    # ### end Alembic commands ###
